### ISSUE TITLE
Colocar o diretório `target` no gitignore?

### ISSUE THREAD

**Issue by lffg** [lucascr91/crustacea#1]
Eu até forkei o repositório pra já mandar uma PR logo de cara, mas acabei ficando na dúvida se isto era intencional. O diretório [`target`](https://github.com/lucascr91/crustacea/tree/main/rust2pythonmodules/vigen/target) realmente deveria estar sendo _commitado_? Geralmente o projeto é _buildado_ no computador do próprio desenvolvedor, até para evitar o envio de um binário de arquitetura não compatível, já que, por padrão ([ver opção `--target`](https://doc.rust-lang.org/cargo/commands/cargo-build.html#compilation-options)), o `cargo build` usa a arquitetura do computador que o invocou como destino do binário.

---

Gostei da iniciativa, até me deu vontade de fazer algo assim também. :-)

**Comment by lucascr91** [comment]
Olá Felipe, 

Pois é, eu nunca commito o `target`. Inclusive, até ontem estava no `.gitignore` mesmo. Hoje que pensei que talvez alguém seguindo o tutorial quisesse ver como fica a estrutura de pastas. 

Mas, pensando bem, commitar o `target` é um _overkill_ para atender essa demanda específica. Vou remover.

E faça um blog sim. É super legal. Estou gostando bastante.
